### ISSUE TITLE
The website is not secure

### ISSUE THREAD

**Issue by QinxinTian** [Whos-Hungry/dashboard-app#119] opened 2017-11-05 03:36 UTC
<img width="1269" alt="2017-11-04 11 33 32" src="https://user-images.githubusercontent.com/25886116/32411715-f4b0e9b2-c1b8-11e7-81aa-f5666d17ee7a.png">
On the left hand side of the address, it should be green if it is really secure.

**Comment by jacobfij** [comment] 2017-11-05 03:58
This is a duplicate of issue #115.

**Closed by jacobfij** 2017-11-05 03:58 UTC
